"""add paper ingestion metadata

Revision ID: 0c5e1222f759
Revises: 61319c900b19
Create Date: 2026-07-29 16:22:04.461839

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c5e1222f759"
down_revision: str | Sequence[str] | None = "61319c900b19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("papers", sa.Column("journal", sa.Text(), nullable=True))
    op.add_column(
        "papers", sa.Column("ingestion_source", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "papers", sa.Column("provider_record_id", sa.String(length=255), nullable=True)
    )
    op.execute(
        sa.text(
            "UPDATE papers "
            "SET ingestion_source = 'unknown' "
            "WHERE ingestion_source IS NULL"
        )
    )

    op.alter_column(
        "papers",
        "ingestion_source",
        existing_type=sa.String(length=100),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "provider_record_id")
    op.drop_column("papers", "ingestion_source")
    op.drop_column("papers", "journal")
    # ### end Alembic commands ###
