"""add paper contents

Revision ID: 1e9ca92b7a85
Revises: 0c5e1222f759
Create Date: 2026-07-30 13:23:22.219942

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e9ca92b7a85"
down_revision: str | Sequence[str] | None = "0c5e1222f759"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("extraction_status", sa.String(length=32), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("parser_version", sa.String(length=100), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(extraction_status = 'succeeded' "
            "AND extracted_text IS NOT NULL "
            "AND checksum IS NOT NULL) "
            "OR extraction_status = 'failed'",
            name="ck_paper_contents_successful_content_has_text",
        ),
        sa.CheckConstraint(
            "content_type IN ('abstract', 'full_text')",
            name="ck_paper_contents_supported_content_type",
        ),
        sa.CheckConstraint(
            "extraction_status IN ('succeeded', 'failed')",
            name="ck_paper_contents_supported_extraction_status",
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_paper_contents_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_contents")),
        sa.UniqueConstraint(
            "paper_id", "content_type", name="uq_paper_contents_paper_id_content_type"
        ),
    )
    op.create_index(
        "ix_paper_contents_checksum", "paper_contents", ["checksum"], unique=False
    )
    op.create_index(
        op.f("ix_paper_contents_paper_id"), "paper_contents", ["paper_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paper_contents_paper_id"), table_name="paper_contents")
    op.drop_index("ix_paper_contents_checksum", table_name="paper_contents")
    op.drop_table("paper_contents")
    # ### end Alembic commands ###
