"""add normalized title to papers

Revision ID: 61319c900b19
Revises: 0eb5db368007
Create Date: 2026-07-27 17:28:07.562663

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61319c900b19"
down_revision: str | Sequence[str] | None = "0eb5db368007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("papers", sa.Column("normalized_title", sa.Text(), nullable=False))
    op.create_index(
        op.f("ix_papers_normalized_title"), "papers", ["normalized_title"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_papers_normalized_title"), table_name="papers")
    op.drop_column("papers", "normalized_title")
    # ### end Alembic commands ###
