"""add paper chunks

Revision ID: bf951eb60f80
Revises: 1e9ca92b7a85
Create Date: 2026-07-31 13:34:24.028916

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf951eb60f80"
down_revision: str | Sequence[str] | None = "1e9ca92b7a85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("paper_content_id", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=32), nullable=False),
        sa.Column("heading", sa.Text(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=False),
        sa.Column("end_char", sa.Integer(), nullable=False),
        sa.Column("paragraph_start_sequence", sa.Integer(), nullable=False),
        sa.Column("paragraph_end_sequence", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("chunker_version", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "section IN ("
            "'abstract', 'background', 'introduction', 'methods', "
            "'results', 'discussion', 'limitations', 'conclusion', "
            "'references', 'other'"
            ")",
            name="ck_paper_chunks_supported_section",
        ),
        sa.CheckConstraint("length(text) > 0", name="ck_paper_chunks_nonempty_text"),
        sa.CheckConstraint(
            "page_number IS NULL OR page_number >= 1",
            name="ck_paper_chunks_positive_page_number",
        ),
        sa.CheckConstraint(
            "paragraph_start_sequence >= 1 "
            "AND paragraph_end_sequence >= paragraph_start_sequence",
            name="ck_paper_chunks_valid_paragraph_range",
        ),
        sa.CheckConstraint(
            "sequence_number >= 1", name="ck_paper_chunks_positive_sequence"
        ),
        sa.CheckConstraint(
            "start_char >= 0 AND end_char > start_char",
            name="ck_paper_chunks_valid_character_range",
        ),
        sa.CheckConstraint(
            "token_count >= 1", name="ck_paper_chunks_positive_token_count"
        ),
        sa.ForeignKeyConstraint(
            ["paper_content_id"],
            ["paper_contents.id"],
            name=op.f("fk_paper_chunks_paper_content_id_paper_contents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_paper_chunks_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_chunks")),
        sa.UniqueConstraint(
            "paper_content_id",
            "sequence_number",
            name="uq_paper_chunks_paper_content_id_sequence_number",
        ),
    )
    op.create_index(
        "ix_paper_chunks_paper_content_id",
        "paper_chunks",
        ["paper_content_id"],
        unique=False,
    )
    op.create_index(
        "ix_paper_chunks_paper_id_section",
        "paper_chunks",
        ["paper_id", "section"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_paper_chunks_paper_id_section", table_name="paper_chunks")
    op.drop_index("ix_paper_chunks_paper_content_id", table_name="paper_chunks")
    op.drop_table("paper_chunks")
    # ### end Alembic commands ###
